### ISSUE TITLE
loading a non-existant image crashes in some circumstances

### ISSUE THREAD

**Issue by umlaeute** [umlaeute/Gem#356]
`[pix_image]` crashes under weird circumstances:

0. make sure only `imageMAGICK` and `imageTIFF` loader-backends are available
1. open an existing TIFF-image `good.tif`
2. then try to open any non-existing image `bad.tif` or `bad.jpg` :boom: 

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff7be1d2f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff7b92ef2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7b7d472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff7b7d395 in __assert_fail_base (fmt=0x7ffff7cf1a70 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff6201cf0 "exception->signature == MagickCoreSignature", 
    file=file@entry=0x7ffff6221d23 "../../magick/exception.c", line=line@entry=1122, function=function@entry=0x7ffff6222a00 "ThrowMagickExceptionList") at ./assert/assert.c:92
#5  0x00007ffff7b8bdf2 in __GI___assert_fail (assertion=0x7ffff6201cf0 "exception->signature == MagickCoreSignature", file=0x7ffff6221d23 "../../magick/exception.c", line=1122, function=0x7ffff6222a00 "ThrowMagickExceptionList")
    at ./assert/assert.c:101
#6  0x00007ffff60ed9a2 in ThrowMagickExceptionList () from /lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6
#7  0x00007ffff60ed2eb in ThrowMagickException () from /lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6
#8  0x00007ffff54b445a in ?? () from /usr/lib/x86_64-linux-gnu/ImageMagick-6.9.11/modules-Q16/coders/tiff.so
#9  0x00007ffff5428141 in ?? () from /lib/x86_64-linux-gnu/libtiff.so.6
#10 0x00007ffff545a835 in TIFFOpenExt () from /lib/x86_64-linux-gnu/libtiff.so.6
#11 0x00007ffff66b9a0b in gem::plugins::imageTIFF::load (this=<optimized out>, filename="/home/zmoelnig/src/puredata/Gem/build-linux/data/ducks.tif", result=..., props=...) at ../../../plugins/TIFF/imageTIFF.cpp:104
#12 0x00007ffff72522e5 in gem::plugins::imageloaderMeta::load (this=0x5555557a46f0, filename="/home/zmoelnig/src/puredata/Gem/build-linux/data/ducks.tif", result=..., props=...) at ../../../src/plugins/imageloader.cpp:132
#13 0x00007ffff71bdab4 in gem::image::PixImageThreadLoader::process (this=<optimized out>, ID=<optimized out>, data=<optimized out>) at /usr/include/c++/12/bits/basic_string.tcc:238
#14 0x00007ffff72350fa in gem::thread::WorkerThread::PIMPL::process (you=0x5555557c4500) at ../../../src/Utils/WorkerThread.cpp:146
#15 0x00007ffff7bdffd4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#16 0x00007ffff7c6066c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by umlaeute** [comment]
there probably is either some memory-corruption going on (or some monkey-patching)...

valgrind says:

```valgrind
==2038810== Invalid read of size 8
==2038810==    at 0x70F37CE: ThrowMagickExceptionList (in /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6.0.0)
==2038810==    by 0x70F32EA: ThrowMagickException (in /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6.0.0)
==2038810==    by 0x75BD459: ??? (in /usr/lib/x86_64-linux-gnu/ImageMagick-6.9.11/modules-Q16/coders/tiff.so)
==2038810==    by 0x9D01140: ??? (in /usr/lib/x86_64-linux-gnu/libtiff.so.6.0.0)
==2038810==    by 0x9D33834: TIFFOpenExt (in /usr/lib/x86_64-linux-gnu/libtiff.so.6.0.0)
==2038810==    by 0x652BA0A: gem::plugins::imageTIFF::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, imageStruct&, gem::Properties&) (imageTIFF.cpp:104)
==2038810==    by 0x57912E4: gem::plugins::imageloaderMeta::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, imageStruct&, gem::Properties&) (imageloader.cpp:132)
==2038810==    by 0x56FBFCD: gem::image::load::sync(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, imageStruct&, gem::Properties&) (ImageLoad.cpp:162)
==2038810==    by 0x56FC3CC: gem::image::load::sync(void (*)(void*, unsigned int, imageStruct*, gem::Properties const&), void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int&) (ImageLoad.cpp:199)
==2038810==    by 0x5981A54: pix_image::openMess(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (pix_image.cpp:103)
==2038810==    by 0x598110F: pix_image::obj_setupCallback(_class*)::_CallbackClass_openMess_241::callback(void*, _symbol*) (pix_image.cpp:241)
==2038810==    by 0x1A660E: pd_typedmess (m_class.c:1086)
==2038810==  Address 0xaabbee0 is 48 bytes inside a block of size 56 free'd
==2038810==    at 0x484317B: free (vg_replace_malloc.c:872)
==2038810==    by 0x712FE6E: RelinquishMagickMemory (in /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6.0.0)
==2038810==    by 0x65C4CA2: Magick::Image::read(MagickCore::_Image*, MagickCore::_ExceptionInfo*) (in /usr/lib/x86_64-linux-gnu/libMagick++-6.Q16.so.8.0.0)
==2038810==    by 0x5B0A17E: gem::plugins::imageMAGICK::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, imageStruct&, gem::Properties&) (MagickPlusPlus.cpp:43)
==2038810==    by 0x57912E4: gem::plugins::imageloaderMeta::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, imageStruct&, gem::Properties&) (imageloader.cpp:132)
==2038810==    by 0x56FBFCD: gem::image::load::sync(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, imageStruct&, gem::Properties&) (ImageLoad.cpp:162)
==2038810==    by 0x56FC3CC: gem::image::load::sync(void (*)(void*, unsigned int, imageStruct*, gem::Properties const&), void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int&) (ImageLoad.cpp:199)
==2038810==    by 0x5981A54: pix_image::openMess(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (pix_image.cpp:103)
==2038810==    by 0x598110F: pix_image::obj_setupCallback(_class*)::_CallbackClass_openMess_241::callback(void*, _symbol*) (pix_image.cpp:241)
==2038810==    by 0x1A660E: pd_typedmess (m_class.c:1086)
==2038810==    by 0x1A9579: outlet_anything (m_obj.c:621)
==2038810==    by 0x1A39E5: binbuf_eval (m_binbuf.c:789)
==2038810==  Block was alloc'd at
==2038810==    at 0x48407B4: malloc (vg_replace_malloc.c:381)
==2038810==    by 0x70F331F: AcquireExceptionInfo (in /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6.0.0)
==2038810==    by 0x65C5310: Magick::Image::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (in /usr/lib/x86_64-linux-gnu/libMagick++-6.Q16.so.8.0.0)
==2038810==    by 0x5B0A17E: gem::plugins::imageMAGICK::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, imageStruct&, gem::Properties&) (MagickPlusPlus.cpp:43)
==2038810==    by 0x57912E4: gem::plugins::imageloaderMeta::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, imageStruct&, gem::Properties&) (imageloader.cpp:132)
==2038810==    by 0x56FBFCD: gem::image::load::sync(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, imageStruct&, gem::Properties&) (ImageLoad.cpp:162)
==2038810==    by 0x56FC3CC: gem::image::load::sync(void (*)(void*, unsigned int, imageStruct*, gem::Properties const&), void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int&) (ImageLoad.cpp:199)
==2038810==    by 0x5981A54: pix_image::openMess(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (pix_image.cpp:103)
==2038810==    by 0x598110F: pix_image::obj_setupCallback(_class*)::_CallbackClass_openMess_241::callback(void*, _symbol*) (pix_image.cpp:241)
==2038810==    by 0x1A660E: pd_typedmess (m_class.c:1086)
==2038810==    by 0x1A9579: outlet_anything (m_obj.c:621)
==2038810==    by 0x1A39E5: binbuf_eval (m_binbuf.c:789)
```

i do not know why `TIFFOpenExt` would call `ThrowMagickException` (it should not)

**Comment by umlaeute** [comment]
installing some more debugging symbols gives us:

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff7be1d2f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff7b92ef2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7b7d472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff7b7d395 in __assert_fail_base (fmt=0x7ffff7cf1a70 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff6201cf0 "exception->signature == MagickCoreSignature", 
    file=file@entry=0x7ffff6221d23 "../../magick/exception.c", line=line@entry=1122, function=function@entry=0x7ffff6222a00 <__PRETTY_FUNCTION__.0> "ThrowMagickExceptionList") at ./assert/assert.c:92
#5  0x00007ffff7b8bdf2 in __GI___assert_fail (assertion=assertion@entry=0x7ffff6201cf0 "exception->signature == MagickCoreSignature", file=file@entry=0x7ffff6221d23 "../../magick/exception.c", line=line@entry=1122, 
    function=function@entry=0x7ffff6222a00 <__PRETTY_FUNCTION__.0> "ThrowMagickExceptionList") at ./assert/assert.c:101
#6  0x00007ffff60ed9a2 in ThrowMagickExceptionList (exception=0x55555584ee90, module=0x7ffff54c5017 "../../coders/tiff.c", function=<optimized out>, line=<optimized out>, severity=CoderError, tag=<optimized out>, 
    format=0x7ffff54c502b "`%s'", operands=0x7fffffffb410) at ../../magick/exception.c:1122
#7  0x00007ffff60ed2eb in ThrowMagickException (exception=<optimized out>, module=<optimized out>, function=<optimized out>, line=<optimized out>, severity=<optimized out>, tag=<optimized out>, format=0x7ffff54c502b "`%s'")
    at ../../magick/exception.c:1160
#8  0x00007ffff54b445a in TIFFErrors (module=0x7ffff5482228 <module> "TIFFOpen", format=0x1f1cc2 <error: Cannot access memory at address 0x1f1cc2>, error=0x6) at ../../coders/tiff.c:606
#9  0x00007ffff5428141 in _TIFFErrorEarly (opts=opts@entry=0x0, clientdata=clientdata@entry=0x0, module=module@entry=0x7ffff5482228 <module> "TIFFOpen", fmt=fmt@entry=0x7ffff548220a "%s: %s") at ./libtiff/tif_error.c:96
#10 0x00007ffff545a835 in TIFFOpenExt (name=0x5555557c5290 "/home/zmoelnig/src/puredata/Gem/build-linux/data/fuu", mode=<optimized out>, opts=0x0) at ./libtiff/tif_unix.c:245
#11 0x00007ffff66b9a0b in gem::plugins::imageTIFF::load (this=<optimized out>, filename="/home/zmoelnig/src/puredata/Gem/build-linux/data/fuu", result=..., props=...) at ../../../plugins/TIFF/imageTIFF.cpp:104
#12 0x00007ffff72522e5 in gem::plugins::imageloaderMeta::load (this=0x5555557a46f0, filename="/home/zmoelnig/src/puredata/Gem/build-linux/data/fuu", result=..., props=...) at ../../../src/plugins/imageloader.cpp:132
```

now `_TiffErrorEarly` (line:9) is a libtiff function, and `TiffErrors` (line:8) is a Magick-function.

the libtiff function calls some optional error-handlers https://github.com/libsdl-org/libtiff/blob/cea60470546fcb8bc1bb937512485aae15367b5d/libtiff/tif_error.c#L93-L98 (note that the canonical repository of libtiff is on [gitlab](https://gitlab.com/libtiff/libtiff/-/blob/master/libtiff/tif_error.c), i'm only referencing some random clone on github for the sake of code-inclusion)
